name: Install playwright
description: Install all dependencies ready for playwright tests

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 24.x
    - name: Install dependencies
      shell: bash
      working-directory: ./tests/Dfe.EarlyYearsQualification.E2ETests
      run: npm ci --ignore-scripts
    - name: Install Playwright Browsers
      shell: bash
      working-directory: ./tests/Dfe.EarlyYearsQualification.E2ETests
      run: npx --ignore-scripts playwright@1.62.1 install chromium firefox webkit --with-deps --no-shell