version: 2
updates:

  - package-ecosystem: github-actions
    directory: /
    cooldown:
      default-days: 7
    schedule:
      interval: 'daily'
    labels:
      - github-actions
      - dependabot

  - package-ecosystem: docker
    directory: /src/Dfe.EarlyYearsQualification.Web
    cooldown:
      default-days: 7
    schedule:
      interval: 'weekly'
    labels:
      - docker
      - dependabot

  - package-ecosystem: nuget
    directory: /
    cooldown:
      default-days: 7
    schedule:
      interval: 'daily'
    labels:
      - nuget
      - dependabot
    ignore:
      - dependency-name: FluentAssertions
        # Ignore versions of FluentAssertions that are equal to or greater than 8.0.0
        versions: [">=8.0.0"]

  - package-ecosystem: npm
    directory: /tests/Dfe.EarlyYearsQualification.E2ETests
    cooldown:
      default-days: 7
    schedule:
      interval: 'daily'
    labels:
      - npm
      - dependabot