name: Run Playwright validation tests
description: Run validation tests using Playwright

inputs:
  webapp_url:
    required: true
    description: 'The webapp url to run against'
  auth_secret:
    required: true
    description: 'The auth secret to use when running the test'
  test_type:
    required: true
    description: 'The type of test to run: smoke or validation'
runs:
  using: composite
  steps:
    - name: Run Playwright tests
      shell: bash
      env:
        WEBAPP_URL: ${{ inputs.webapp_url }}
        AUTH_SECRET: ${{ inputs.auth_secret }}
        TEST_TYPE: ${{ inputs.test_type }}
      working-directory: ./tests/Dfe.EarlyYearsQualification.E2ETests
      run: WEBAPP_URL="https://${WEBAPP_URL}" DOMAIN="https://${WEBAPP_URL}" AUTH_SECRET="${AUTH_SECRET}" npx playwright test --grep "@${TEST_TYPE}"
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30