name: Run Playwright smoke tests
description: Run smoke tests using Playwright

inputs:
  webapp_url:
    required: true
    type: string
  auth_secret:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Run Playwright tests
      shell: bash
      working-directory: ./tests/Dfe.EarlyYearsQualification.E2ETests
      run: WEBAPP_URL=https://${{ inputs.webapp_url }}.azurewebsites.net DOMAIN=https://${{ inputs.webapp_url }}.azurewebsites.net AUTH_SECRET=${{ inputs.auth_secret }} npx playwright test --grep "@smoke"
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30