name: Run Playwright smoke tests
description: Run smoke tests using Playwright

inputs:
  webapp_url:
    required: true
    type: string
  auth_secret:
    required: true
    type: string

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      shell: bash
      working-directory: ./tests/Dfe.EarlyYearsQualification.SmokeTests
      run: npm ci
    - name: Install Playwright Browsers
      shell: bash
      working-directory: ./tests/Dfe.EarlyYearsQualification.SmokeTests
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      shell: bash
      working-directory: ./tests/Dfe.EarlyYearsQualification.SmokeTests
      run: WEBAPP_URL=https://${{ inputs.webapp_url }}.azurewebsites.net DOMAIN=https://${{ inputs.webapp_url }}.azurewebsites.net AUTH_SECRET=${{ inputs.auth_secret }} npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30