name: Run Cypress E2E tests
description: Run E2E tests using Cypress

inputs:
  url:
    required: true
    type: string

runs:
  using: composite

  steps:
    - name: Run Chrome Tests
      uses: cypress-io/github-action@v6
      if: success() || failure()
      with:
        working-directory: ./tests/Dfe.EarlyYearsQualification.E2ETests/
        browser: chrome
        config: baseUrl="${{ inputs.url }}"

    # COMMENTED OUT TEMPORARILY AS CYPRESS HAS AN ISSUE WITH FIREFOX 124: https://github.com/cypress-io/cypress/issues/29172
    # - name: Run Firefox Tests
    #   uses: cypress-io/github-action@v6
    #   if: success() || failure()
    #   with:
    #     working-directory: ./tests/Dfe.EarlyYearsQualification.E2ETests/
    #     browser: firefox
    #     config: baseUrl="${{ inputs.url }}"

    - name: Store screenshots on test failure
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-screenshots
        path: ./tests/Dfe.EarlyYearsQualification.E2ETests/cypress/screenshots