name: Run Cypress E2E tests
description: Run E2E tests using Cypress

inputs:
  url:
    required: true
    type: string

runs:
  using: composite

  env:
    WORKING_DIRECTORY: ./tests/Dfe.EarlyYearsQualification.E2ETests/

  steps:
    - name: Build and test project
      uses: cypress-io/github-action@v6
      with:
        working-directory: ${{ env.WORKING_DIRECTORY }}
        browser: chrome
        #config: baseUrl=${{ inputs.url }} // TODO: Update this once the code check workflow starts running the app locally. For now leave this as the baseUrl in the config file.

    - name: Store screenshots on test failure
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-screenshots
        path: ${{ env.WORKING_DIRECTORY }}cypress/screenshots