name: Run Unit Tests
description: Runs the unit tests and publishes them to the workflow runs

inputs:
  solution_filename:
    required: true
    type: string

runs:
  using: composite

  steps:
    - name: Test
      shell: bash
      run: dotnet test ${{ inputs.solution_filename }} --no-restore --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage || true --settings coverlet.runsettings

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      if: github.actor != 'dependabot[bot]' # dependabot PRs have issues accessing the resource so skip
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '75 90'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
    
    - name: Write to Job Summary
      shell: bash
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY