name: Run Playwright webkit end to end tests
description: Run webkit end to end tests using Playwright

inputs:
  webapp_url:
    required: true
    description: 'The webapp url to run against'

runs:
  using: composite
  steps:
    - name: Run Playwright webkit tests
      shell: bash
      working-directory: ./tests/Dfe.EarlyYearsQualification.E2ETests
      env:
        WEBAPP_URL: ${{ inputs.webapp_url }}
        CI: true
      run: WEBAPP_URL=${WEBAPP_URL} UPGRADE_INSECURE_REQUESTS=false npx playwright test --workers=1 --grep "@e2e" --project=webkit
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-webkit-report
        path: ./tests/Dfe.EarlyYearsQualification.E2ETests/playwright-report/
        retention-days: 30