name: Run Playwright snapshot tests
description: Run snapshot test using Playwright

runs:
  using: composite
  steps:
    - name: Run Playwright tests
      shell: bash
      working-directory: ./tests/Dfe.EarlyYearsQualification.E2ETests
      env:
        CI: true
      run: npx playwright test --workers=4 --grep "@snapshot" --project chromium
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: test-results
        path: ./tests/Dfe.EarlyYearsQualification.E2ETests/test-results/
        retention-days: 30