name: Run accessibility tests
description: Runs Pa11y-ci

inputs:
  url:
    required: true
    type: string
  auth_secret:
    required: true
    type: string

runs:
  using: composite

  steps:
    - name: Run Pa11y
      shell: bash
      env:
        AUTH_SECRET: ${{ inputs.auth_secret }}
        URL: ${{ inputs.url }}
      run: npm install -g pa11y-ci && export AUTH_SECRET="${AUTH_SECRET}" && pa11y-ci "${URL}" --config .pa11yci-ubuntu.js
      working-directory: ./tests/Dfe.EarlyYearsQualification.AccessibilityTests/
      
    