name: Run accessibility tests
description: Runs Pa11y-ci

inputs:
  url:
    required: true
    type: string
  auth_secret:
    required: true
    type: string

runs:
  using: composite

  steps:
    - name: Run Pa11y
      shell: bash
      run: npm install -g pa11y-ci && export AUTH_SECRET=${{ inputs.auth_secret }} && pa11y-ci ${{ inputs.url }} --config .pa11yci-ubuntu.json
      working-directory: ./tests/Dfe.EarlyYearsQualification.AccessibilityTests/
      
    