name: Run app for testing
description: Run the app within the action so we can run E2E and Accessibility tests.

inputs:
  url:
    required: true
    type: string

runs:
  using: composite

  steps:
    - name: Run .Net Project
      shell: bash
      run: |
        dotnet run --urls "${{ inputs.url }}" --project="src/Dfe.EarlyYearsQualification.Web" \
        --UseMockContentful=true \
        --ServiceAccess:Keys:0={{ secrets.WEBAPP_E2E_ACCESS_KEY }} \
        --ServiceAccess:Keys:1={{ secrets.WEBAPP_TEAM_ACCESS_KEY }} \
        --ServiceAccess:Keys:2={{ secrets.WEBAPP_ACCESS_KEY_1 }} \
        --ServiceAccess:Keys:3={{ secrets.WEBAPP_ACCESS_KEY_2 }} &
