name: Run app for testing
description: Run the app within the action so we can run E2E and Accessibility tests.

inputs:
  url:
    description: "URL used by the app to listen"
    required: true
    type: string
  auth_secret:
    description: "Auth secret used by end-to-end tests"
    required: true
    type: string


runs:
  using: composite

  steps:
    - name: Run .Net Project
      shell: bash
      run: |
        dotnet run --urls "${{ inputs.url }}" --project="src/Dfe.EarlyYearsQualification.Web" \
        --UseMockContentful=true \
        --ServiceAccess:Keys:0="${{ inputs.auth_secret }}" \
        --Environment=Development &
