name: Run Playwright end to end tests
description: Run end to end tests using Playwright

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - name: Install dependencies
      shell: bash
      working-directory: ./tests/Dfe.EarlyYearsQualification.E2ETests
      run: npm ci
    - name: Install Playwright Browsers
      shell: bash
      working-directory: ./tests/Dfe.EarlyYearsQualification.E2ETests
      run: npx playwright install --with-deps --no-shell
    - name: Run Playwright tests
      shell: bash
      working-directory: ./tests/Dfe.EarlyYearsQualification.E2ETests
      env:
        CI: true
      run: npx playwright test --workers=10
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30