name: Run Playwright end to end tests
description: Run end to end tests using Playwright

inputs:
  webapp_url:
    required: true
    description: 'The webapp url to run against'

runs:
  using: composite
  steps:
    - name: Run Playwright tests
      shell: bash
      working-directory: ./tests/Dfe.EarlyYearsQualification.E2ETests
      env:
        WEBAPP_URL: ${{ inputs.webapp_url }}
        CI: true
      run: WEBAPP_URL=${WEBAPP_URL} npx playwright test --workers=4 --grep "@e2e" --project=chromium --project=firefox
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: ./tests/Dfe.EarlyYearsQualification.E2ETests/playwright-report/
        retention-days: 30