name: Run Playwright end to end tests
description: Run end to end tests using Playwright

runs:
  using: composite
  steps:
    - name: Run Playwright tests
      shell: bash
      working-directory: ./tests/Dfe.EarlyYearsQualification.E2ETests
      env:
        CI: true
      run: npx playwright test --workers=4 --grep "@e2e"
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: ./tests/Dfe.EarlyYearsQualification.E2ETests/playwright-report/
        retention-days: 30