import {test, expect} from '@playwright/test';
import {
    startJourney,
    checkingOwnQualificationOrSomeoneElsesPage,
    whereWasTheQualificationAwarded,
    startedOnOrAfterSeptember2014,
    whenWasQualificationAwarded,
    whatLevelIsTheQualification,
    selectNotOnTheListAsTheAwardingOrganisation,
    checkYourAnswersPage,
    selectQualification,
    checkText,
    chooseStartDateOptionBasedOnDate,
    selectICannotFindTheQualification,
    confirmQualification,
    processAdditionalRequirement,
    confirmAdditonalRequirementsAnswers,
    checkDetailsPage,
    whatIsTheAwardingOrganisationValue,
    doesNotExist
} from '../_shared/playwrightWrapper';
import {
    approved,
    approvedLevel2ContentNFRAndPaediatricFirstAidCertificate,
    approvedLevel2MaybePaediatricFirstAidCertificate,
    approvedLevel2PaediatricFirstAidCertificate,
    approvedLevel3Level2English,
    approvedLevel3Level2EnglishMaybePaediatricFirstAidCertificate,
    approvedLevel3Level2EnglishPaediatricFirstAidCertificate,
    ebrLevel3,
    level2QualificationNotFullAndRelevantRatioContent,
    level2QualificationNotFullAndRelevantStartedBetweenSeptember2014AndAugust2019RatioContent,
    level36QualificationNotFullAndRelevantStartedBetweenSep2014AndAug2019Heading,
    level36QualificationNotFullAndRelevantStartedBetweenSep2014AndAug2019HeadingContent,
    level6EBRContentEYITT,
    level6NotApprovedContentQTSEYTSEYPS,
    level6QualificationApprovedLevel2ContentNFRAndPaediatricFirstAidCertificates,
    noAdditionalRequirements,
    notApproved,
    possibleRouteAvailable,
    qualificationFullAndRelevantHeading,
    qualificationFullAndRelevantHeadingContent,
    qualificationLevel345NotFullAndRelevantStartedBetweenSep2014AndAug2019Heading,
    qualificationLevel345NotFullAndRelevantStartedBetweenSep2014AndAug2019HeadingContent,
    qualificationNotFullAndRelevantHeading,
    qualificationNotFullAndRelevantHeadingContent,
    ratioRequirmentAlternativeRouteContent,
} from './regression-test-content';

type Scenario = {
    scenarioName: string,
    scenarioId: number,
    monthStarted: string,
    yearStarted: string,
    monthAwarded: string,
    yearAwarded: string,
    selectedLevel: number,
    selectedAwardingOrganisation: string,
    qualificationToSelect: string,
    additionalRequirements: AdditionalRequirement[]
    expectedContent: ExpectedContent[]
}

type ExpectedContent = {
    fullAndRelevantHeading: string,
    fullAndRelevantContent: string,
    staffChildsRatiosContent?: string,
    ratioRequirementContent: RatioRequirementContent[],
}

type RatioRequirementContent = {
    level: string,
    expectedContent: string,
    approvalStatus: string,
    headerId: string,
    contentId: string,
    approvalId: string
}

type AdditionalRequirement = {
    index: number,
    answer: string
}

const noAtQuestionOne: AdditionalRequirement = { index: 1, answer: '#no' };
const noAtQuestionTwo: AdditionalRequirement = { index: 2, answer: '#no' };
const noAtQuestionThree: AdditionalRequirement = { index: 3, answer: '#no' };
const yesAtQuestionOne: AdditionalRequirement = { index: 1, answer: '#yes' };

const createScenario = (overrides: Partial<Scenario>): Scenario => ({
    scenarioName: "",
    scenarioId: 0,
    monthStarted: "",
    yearStarted: "",
    monthAwarded: "",
    yearAwarded: "",
    selectedLevel: 0,
    additionalRequirements: [],
    selectedAwardingOrganisation: "",
    qualificationToSelect: "",
    expectedContent: [],
    ...overrides
});

const createRatioRequirement = (
    level: string,
    approvalStatus: string,
    expectedContent = '',
): RatioRequirementContent => ({
    level,
    expectedContent,
    approvalStatus,
    headerId: `${level.replace(' ', '\\ ')}_heading`,
    contentId: `ratio-${level.replace(' ', '')}-additional-info`,
    approvalId: `ratio-${level.replace(' ', '')}-tag`,
});

const createExpectedContent = (
    fullAndRelevantHeading: string,
    fullAndRelevantContent: string,
    ratioRequirementContent: RatioRequirementContent[],
    staffChildsRatiosContent?: string,
): ExpectedContent => ({
    fullAndRelevantHeading,
    fullAndRelevantContent,
    staffChildsRatiosContent,
    ratioRequirementContent,
});

type ExpectedContentOverrides = {
    fullAndRelevantHeading?: string,
    fullAndRelevantContent?: string,
    staffChildsRatiosContent?: string,
}

const createSingleRatioExpectedContent = (
    level: string,
    approvalStatus: string,
    expectedContent = '',
    overrides: ExpectedContentOverrides = {},
): ExpectedContent[] => [
    createExpectedContent(
        overrides.fullAndRelevantHeading ?? qualificationFullAndRelevantHeading,
        overrides.fullAndRelevantContent ?? qualificationFullAndRelevantHeadingContent,
        [createRatioRequirement(level, approvalStatus, expectedContent)],
        overrides.staffChildsRatiosContent,
    ),
];

const level2Scenarios: Scenario[] = [
    createScenario({
        scenarioName: 'Level 2 - Approved - Awarded before September 2016 - No other requirements',
        scenarioId: 1,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "01",
        yearAwarded: "2013",
        selectedLevel: 2,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-001",
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, noAdditionalRequirements),
    }),
    createScenario({
        scenarioName: 'Level 2 - Approved - Awarded in June 2016 - Maybe Paediatric first aid certificate',
        scenarioId: 2,
        monthStarted: "01",
        yearStarted: "2013",
        monthAwarded: "06",
        yearAwarded: "2016",
        selectedLevel: 2,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-001",
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, approvedLevel2MaybePaediatricFirstAidCertificate),
    }),
    createScenario({
        scenarioName: 'Level 2 - Approved - Awarded after June 2016 - Paediatric first aid certificate',
        scenarioId: 3,
        monthStarted: "01",
        yearStarted: "2013",
        monthAwarded: "06",
        yearAwarded: "2018",
        selectedLevel: 2,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-001",
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, approvedLevel2PaediatricFirstAidCertificate),
    }),
    createScenario({
        scenarioName: 'Level 2 - Not Approved - Null requirements',
        scenarioId: 4,
        monthStarted: "01",
        yearStarted: "2013",
        monthAwarded: "06",
        yearAwarded: "2018",
        selectedLevel: 2,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-300",
        additionalRequirements: [noAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 2', notApproved, '', {
            fullAndRelevantHeading: qualificationNotFullAndRelevantHeading,
            fullAndRelevantContent: qualificationNotFullAndRelevantHeadingContent,
            staffChildsRatiosContent: level2QualificationNotFullAndRelevantRatioContent,
        }),
    }),
    createScenario({
        scenarioName: 'Level 3 - Not Approved - If the Level 2 qualification is NOT full and relevant - No other requirements',
        scenarioId: 5,
        monthStarted: "01",
        yearStarted: "2013",
        monthAwarded: "06",
        yearAwarded: "2018",
        selectedLevel: 2,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-300",
        additionalRequirements: [noAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 3', notApproved, '', {
            fullAndRelevantHeading: qualificationNotFullAndRelevantHeading,
            fullAndRelevantContent: qualificationNotFullAndRelevantHeadingContent,
            staffChildsRatiosContent: level2QualificationNotFullAndRelevantRatioContent,
        }),
    }),
    createScenario({
        scenarioName: 'Level 3 - Not Approved - If the Level 2 qualification is NOT full and relevant - No other requirements',
        scenarioId: 6,
        monthStarted: "01",
        yearStarted: "2013",
        monthAwarded: "06",
        yearAwarded: "2018",
        selectedLevel: 2,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-300",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 3', possibleRouteAvailable, ebrLevel3),
    }),
    createScenario({
        scenarioName: 'Level 6 - Not Approved - Null requirements',
        scenarioId: 7,
        monthStarted: "01",
        yearStarted: "2013",
        monthAwarded: "06",
        yearAwarded: "2018",
        selectedLevel: 2,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-300",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 6', notApproved),
    }),
];

const level3Scenarios: Scenario[] = [
    createScenario({
        scenarioName: 'Level 2 - Approved - Awarded before June 2016 - No other requirements',
        scenarioId: 8,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "01",
        yearAwarded: "2013",
        selectedLevel: 3,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-077",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, noAdditionalRequirements),
    }),
    createScenario({
        scenarioName: 'Level 2 - Approved - Awarded in June 2016 - Maybe Paediatric first aid certificate',
        scenarioId: 9,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "06",
        yearAwarded: "2016",
        selectedLevel: 3,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-077",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, approvedLevel2MaybePaediatricFirstAidCertificate),
    }),
    createScenario({
        scenarioName: 'Level 2 - Approved - Awarded after June 2016 - Paediatric first aid certificate',
        scenarioId: 10,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "06",
        yearAwarded: "2018",
        selectedLevel: 3,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-077",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, approvedLevel2PaediatricFirstAidCertificate),
    }),
    createScenario({
        scenarioName: "Level 2 - Approved - started between September 2014 and August 2019 and awarded before June 2016 - Explanation of why the qualification is approved even though it's not full and relevant",
        scenarioId: 11,
        monthStarted: "01",
        yearStarted: "2015",
        monthAwarded: "10",
        yearAwarded: "2015",
        selectedLevel: 3,
        selectedAwardingOrganisation: "NCFE",
        qualificationToSelect: "EYQ-224",
        additionalRequirements: [noAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, approvedLevel2ContentNFRAndPaediatricFirstAidCertificate, {
            fullAndRelevantHeading: qualificationLevel345NotFullAndRelevantStartedBetweenSep2014AndAug2019Heading,
            fullAndRelevantContent: qualificationLevel345NotFullAndRelevantStartedBetweenSep2014AndAug2019HeadingContent,
            staffChildsRatiosContent: level2QualificationNotFullAndRelevantStartedBetweenSeptember2014AndAugust2019RatioContent,
        }),
    }),
    createScenario({
        scenarioName: "Level 2 - Approved - started between September 2014 and August 2019 and awarded in June 2016 - Explanation of why the qualification is approved even though it's not full and relevant + Maybe paediatric first aid certificate",
        scenarioId: 12,
        monthStarted: "01",
        yearStarted: "2015",
        monthAwarded: "06",
        yearAwarded: "2016",
        selectedLevel: 3,
        selectedAwardingOrganisation: "NCFE",
        qualificationToSelect: "EYQ-224",
        additionalRequirements: [noAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, approvedLevel2ContentNFRAndPaediatricFirstAidCertificate, {
            fullAndRelevantHeading: qualificationLevel345NotFullAndRelevantStartedBetweenSep2014AndAug2019Heading,
            fullAndRelevantContent: qualificationLevel345NotFullAndRelevantStartedBetweenSep2014AndAug2019HeadingContent,
            staffChildsRatiosContent: level2QualificationNotFullAndRelevantStartedBetweenSeptember2014AndAugust2019RatioContent,
        }),
    }),
    createScenario({
        scenarioName: "Level 2 - Approved - started between September 2014 and August 2019 and awarded after June 2016 - Explanation of why the qualification is approved even though it's not full and relevant + Paediatric first aid certificate",
        scenarioId: 13,
        monthStarted: "01",
        yearStarted: "2015",
        monthAwarded: "07",
        yearAwarded: "2016",
        selectedLevel: 3,
        selectedAwardingOrganisation: "NCFE",
        qualificationToSelect: "EYQ-224",
        additionalRequirements: [noAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, approvedLevel2ContentNFRAndPaediatricFirstAidCertificate, {
            fullAndRelevantHeading: qualificationLevel345NotFullAndRelevantStartedBetweenSep2014AndAug2019Heading,
            fullAndRelevantContent: qualificationLevel345NotFullAndRelevantStartedBetweenSep2014AndAug2019HeadingContent,
            staffChildsRatiosContent: level2QualificationNotFullAndRelevantStartedBetweenSeptember2014AndAugust2019RatioContent,
        }),
    }),
    createScenario({
        scenarioName: 'Level 2 - Not Approved - No other requirements',
        scenarioId: 14,
        monthStarted: "01",
        yearStarted: "2014",
        monthAwarded: "04",
        yearAwarded: "2022",
        selectedLevel: 3,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-077",
        additionalRequirements: [noAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 2', notApproved, '', {
            fullAndRelevantHeading: qualificationNotFullAndRelevantHeading,
            fullAndRelevantContent: qualificationNotFullAndRelevantHeadingContent,
            staffChildsRatiosContent: level2QualificationNotFullAndRelevantRatioContent,
        }),
    }),
    createScenario({
        scenarioName: 'Level 3 - Approved - Awarded before September 2014 - No other requirements',
        scenarioId: 15,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "04",
        yearAwarded: "2013",
        selectedLevel: 3,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-077",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 3', approved, noAdditionalRequirements),
    }),
    createScenario({
        scenarioName: 'Level 3 - Approved - Awarded between September 2014 and May 2016 - Level 2 English qualification',
        scenarioId: 16,
        monthStarted: "10",
        yearStarted: "2014",
        monthAwarded: "04",
        yearAwarded: "2015",
        selectedLevel: 3,
        selectedAwardingOrganisation: "NCFE",
        qualificationToSelect: "EYQ-224",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 3', approved, approvedLevel3Level2English),
    }),
    createScenario({
        scenarioName: 'Level 3 - Approved - Awarded in June 2016 - Level 2 English qualification + maybe Paediatric first aid certificate',
        scenarioId: 17,
        monthStarted: "10",
        yearStarted: "2014",
        monthAwarded: "06",
        yearAwarded: "2016",
        selectedLevel: 3,
        selectedAwardingOrganisation: "NCFE",
        qualificationToSelect: "EYQ-224",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 3', approved, approvedLevel3Level2EnglishMaybePaediatricFirstAidCertificate),
    }),
    createScenario({
        scenarioName: 'Level 3 - Approved - Awarded after June 2016 - Level 2 English qualification + Paediatric first aid certificate',
        scenarioId: 18,
        monthStarted: "10",
        yearStarted: "2014",
        monthAwarded: "07",
        yearAwarded: "2016",
        selectedLevel: 3,
        selectedAwardingOrganisation: "NCFE",
        qualificationToSelect: "EYQ-224",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 3', approved, approvedLevel3Level2EnglishPaediatricFirstAidCertificate),
    }),
    createScenario({
        scenarioName: 'Level 3 - Possible route available - Level 3 or above qualification that is NOT full and relevant - Experience-based route (EBR)',
        scenarioId: 19,
        monthStarted: "01",
        yearStarted: "2015",
        monthAwarded: "10",
        yearAwarded: "2015",
        selectedLevel: 3,
        selectedAwardingOrganisation: "NCFE",
        qualificationToSelect: "EYQ-224",
        additionalRequirements: [noAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 3', possibleRouteAvailable, ebrLevel3, {
            fullAndRelevantHeading: qualificationLevel345NotFullAndRelevantStartedBetweenSep2014AndAug2019Heading,
            fullAndRelevantContent: qualificationLevel345NotFullAndRelevantStartedBetweenSep2014AndAug2019HeadingContent,
            staffChildsRatiosContent: level2QualificationNotFullAndRelevantStartedBetweenSeptember2014AndAugust2019RatioContent,
        }),
    }),
    createScenario({
        scenarioName: 'Level 6 - Not approved - No other requirements',
        scenarioId: 20,
        monthStarted: "01",
        yearStarted: "2015",
        monthAwarded: "10",
        yearAwarded: "2015",
        selectedLevel: 3,
        selectedAwardingOrganisation: "NCFE",
        qualificationToSelect: "EYQ-224",
        additionalRequirements: [noAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 6', notApproved, '', {
            fullAndRelevantHeading: qualificationLevel345NotFullAndRelevantStartedBetweenSep2014AndAug2019Heading,
            fullAndRelevantContent: qualificationLevel345NotFullAndRelevantStartedBetweenSep2014AndAug2019HeadingContent,
            staffChildsRatiosContent: level2QualificationNotFullAndRelevantStartedBetweenSeptember2014AndAugust2019RatioContent,
        }),
    }),
];

const level4Scenarios: Scenario[] = [
    createScenario({
        scenarioName: 'Level 2 - Approved - Awarded before June 2016 - No other requirements',
        scenarioId: 21,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "01",
        yearAwarded: "2013",
        selectedLevel: 4,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-090",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, noAdditionalRequirements),
    }),
    createScenario({
        scenarioName: 'Level 2 - Approved - Awarded in June 2016 - Maybe Paediatric first aid certificate',
        scenarioId: 22,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "06",
        yearAwarded: "2016",
        selectedLevel: 4,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-090",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, approvedLevel2MaybePaediatricFirstAidCertificate),
    }),
    createScenario({
        scenarioName: 'Level 2 - Approved - Awarded after June 2016 - Paediatric first aid certificate',
        scenarioId: 23,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "06",
        yearAwarded: "2018",
        selectedLevel: 4,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-090",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, approvedLevel2PaediatricFirstAidCertificate),
    }),
    createScenario({
        scenarioName: 'Level 3 - Approved - Awarded before September 2014 - No other requirements',
        scenarioId: 24,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "04",
        yearAwarded: "2013",
        selectedLevel: 4,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-100",
        expectedContent: createSingleRatioExpectedContent('Level 3', approved, noAdditionalRequirements),
    }),
    createScenario({
        scenarioName: 'Level 3 - Approved - Awarded between September 2014 and May 2016 - Level 2 English qualification',
        scenarioId: 25,
        monthStarted: "10",
        yearStarted: "2014",
        monthAwarded: "04",
        yearAwarded: "2015",
        selectedLevel: 4,
        selectedAwardingOrganisation: "NCFE",
        qualificationToSelect: "EYQ-253",
        expectedContent: createSingleRatioExpectedContent('Level 3', approved, approvedLevel3Level2English),
    }),
    createScenario({
        scenarioName: 'Level 3 - Approved - Awarded in June 2016 - Level 2 English qualification + maybe Paediatric first aid certificate',
        scenarioId: 26,
        monthStarted: "10",
        yearStarted: "2014",
        monthAwarded: "06",
        yearAwarded: "2016",
        selectedLevel: 4,
        selectedAwardingOrganisation: "NCFE",
        qualificationToSelect: "EYQ-253",
        expectedContent: createSingleRatioExpectedContent('Level 3', approved, approvedLevel3Level2EnglishMaybePaediatricFirstAidCertificate),
    }),
    createScenario({
        scenarioName: 'Level 3 - Approved - Awarded after June 2016 - Level 2 English qualification + Paediatric first aid certificate',
        scenarioId: 27,
        monthStarted: "10",
        yearStarted: "2014",
        monthAwarded: "07",
        yearAwarded: "2016",
        selectedLevel: 4,
        selectedAwardingOrganisation: "NCFE",
        qualificationToSelect: "EYQ-253",
        expectedContent: createSingleRatioExpectedContent('Level 3', approved, approvedLevel3Level2EnglishPaediatricFirstAidCertificate),
    }),
    createScenario({
        scenarioName: 'Level 3 - Possible route available - Level 3 or above qualification that is NOT full and relevant - Experience-based route (EBR)',
        scenarioId: 28,
        monthStarted: "01",
        yearStarted: "2011",
        monthAwarded: "10",
        yearAwarded: "2013",
        selectedLevel: 4,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-090",
        additionalRequirements: [noAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 3', possibleRouteAvailable, ebrLevel3, {
            fullAndRelevantHeading: qualificationNotFullAndRelevantHeading,
            fullAndRelevantContent: qualificationNotFullAndRelevantHeadingContent,
            staffChildsRatiosContent: level2QualificationNotFullAndRelevantRatioContent,
        }),
    }),
    createScenario({
        scenarioName: 'Level 6 - Not approved - No other requirements',
        scenarioId: 29,
        monthStarted: "01",
        yearStarted: "2015",
        monthAwarded: "10",
        yearAwarded: "2015",
        selectedLevel: 4,
        selectedAwardingOrganisation: "NCFE",
        qualificationToSelect: "EYQ-254",
        expectedContent: createSingleRatioExpectedContent('Level 6', notApproved),
    }),
];

const level5Scenarios: Scenario[] = [
    createScenario({
        scenarioName: 'Level 2 - Approved - Awarded before June 2016 - No other requirements',
        scenarioId: 30,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "01",
        yearAwarded: "2013",
        selectedLevel: 5,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-147",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, noAdditionalRequirements),
    }),
    createScenario({
        scenarioName: 'Level 2 - Approved - Awarded in June 2016 - Maybe Paediatric first aid certificate',
        scenarioId: 31,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "06",
        yearAwarded: "2016",
        selectedLevel: 5,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-147",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, approvedLevel2MaybePaediatricFirstAidCertificate),
    }),
    createScenario({
        scenarioName: 'Level 2 - Approved - Awarded after June 2016 - Paediatric first aid certificate',
        scenarioId: 32,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "06",
        yearAwarded: "2018",
        selectedLevel: 5,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-147",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, approvedLevel2PaediatricFirstAidCertificate),
    }),

    // Level 3 scenarios

    createScenario({
        scenarioName: 'Level 3 - Approved - Awarded before September 2014 - No other requirements',
        scenarioId: 33,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "04",
        yearAwarded: "2013",
        selectedLevel: 5,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-158",
        expectedContent: createSingleRatioExpectedContent('Level 3', approved, noAdditionalRequirements),
    }),
    createScenario({
        scenarioName: 'Level 3 - Approved - Awarded between September 2014 and May 2016 - Level 2 English qualification',
        scenarioId: 34,
        monthStarted: "10",
        yearStarted: "2014",
        monthAwarded: "04",
        yearAwarded: "2015",
        selectedLevel: 5,
        selectedAwardingOrganisation: "NCFE",
        qualificationToSelect: "EYQ-262",
        expectedContent: createSingleRatioExpectedContent('Level 3', approved, approvedLevel3Level2English),
    }),
    createScenario({
        scenarioName: 'Level 3 - Approved - Awarded in June 2016 - Level 2 English qualification + maybe Paediatric first aid certificate',
        scenarioId: 35,
        monthStarted: "10",
        yearStarted: "2014",
        monthAwarded: "06",
        yearAwarded: "2016",
        selectedLevel: 5,
        selectedAwardingOrganisation: "NCFE",
        qualificationToSelect: "EYQ-262",
        expectedContent: createSingleRatioExpectedContent('Level 3', approved, approvedLevel3Level2EnglishMaybePaediatricFirstAidCertificate),
    }),
    createScenario({
        scenarioName: 'Level 3 - Approved - Awarded after June 2016 - Level 2 English qualification + Paediatric first aid certificate',
        scenarioId: 36,
        monthStarted: "10",
        yearStarted: "2014",
        monthAwarded: "07",
        yearAwarded: "2016",
        selectedLevel: 5,
        selectedAwardingOrganisation: "NCFE",
        qualificationToSelect: "EYQ-262",
        expectedContent: createSingleRatioExpectedContent('Level 3', approved, approvedLevel3Level2EnglishPaediatricFirstAidCertificate),
    }),
    createScenario({
        scenarioName: 'Level 3 - Possible route available - Level 3 or above qualification that is NOT full and relevant - Experience-based route (EBR)',
        scenarioId: 37,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "10",
        yearAwarded: "2013",
        selectedLevel: 5,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-147",
        additionalRequirements: [noAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 3', possibleRouteAvailable, ebrLevel3, {
            fullAndRelevantHeading: qualificationNotFullAndRelevantHeading,
            fullAndRelevantContent: qualificationNotFullAndRelevantHeadingContent,
            staffChildsRatiosContent: level2QualificationNotFullAndRelevantRatioContent,
        }),
    }),
    createScenario({
        scenarioName: 'Level 6 - Not approved - No other requirements',
        scenarioId: 38,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "10",
        yearAwarded: "2013",
        selectedLevel: 5,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-147",
        additionalRequirements: [noAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 6', notApproved, '', {
            fullAndRelevantHeading: qualificationNotFullAndRelevantHeading,
            fullAndRelevantContent: qualificationNotFullAndRelevantHeadingContent,
            staffChildsRatiosContent: level2QualificationNotFullAndRelevantRatioContent,
        }),
    }),
];

const level6Scenarios: Scenario[] = [
    createScenario({
        scenarioName: 'Level 2 - Approved - Awarded before June 2016 - No other requirements',
        scenarioId: 39,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "05",
        yearAwarded: "2016",
        selectedLevel: 6,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-192",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, noAdditionalRequirements),
    }),
    createScenario({
        scenarioName: "Level 2 - Approved - Awarded in June 2016 - Maybe Paediatric first aid certificate Exception: if the qualification is approved at level 6, there aren't any requirements",
        scenarioId: 40,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "06",
        yearAwarded: "2016",
        selectedLevel: 6,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-192",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, noAdditionalRequirements),
    }),
    createScenario({
        scenarioName: "Level 2 - Approved - Awarded in June 2016 - Maybe Paediatric first aid certificate Exception: if the qualification is approved at level 6, there aren't any requirements",
        scenarioId: 41,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "06",
        yearAwarded: "2016",
        selectedLevel: 6,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-192",
        additionalRequirements: [noAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, approvedLevel2MaybePaediatricFirstAidCertificate),
    }),
    createScenario({
        scenarioName: "Level 2 - Approved - Awarded after June 2016 - Maybe Paediatric first aid certificate Exception: if the qualification is approved at level 6, there aren't any requirements",
        scenarioId: 42,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "07",
        yearAwarded: "2016",
        selectedLevel: 6,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-192",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, noAdditionalRequirements),
    }),
    createScenario({
        scenarioName: "Level 2 - Approved - Awarded after June 2016 - Maybe Paediatric first aid certificate Exception: if the qualification is approved at level 6, there aren't any requirements",
        scenarioId: 43,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "07",
        yearAwarded: "2016",
        selectedLevel: 6,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-192",
        additionalRequirements: [noAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, approvedLevel2PaediatricFirstAidCertificate),
    }),

    // TODO might break peadiatric first aid certificate
    createScenario({
        scenarioName: "Level 2 - Approved - started between September 2014 and August 2019 and awarded before June 2016 - Explanation of why the qualification is approved even though it's not full and relevant + Paediatric first aid certificate",
        scenarioId: 44,
        monthStarted: "01",
        yearStarted: "2015",
        monthAwarded: "10",
        yearAwarded: "2015",
        selectedLevel: 6,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-293",
        additionalRequirements: [noAtQuestionOne, noAtQuestionTwo, noAtQuestionThree],
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, level6QualificationApprovedLevel2ContentNFRAndPaediatricFirstAidCertificates, {
            fullAndRelevantHeading: level36QualificationNotFullAndRelevantStartedBetweenSep2014AndAug2019Heading,
            fullAndRelevantContent: level36QualificationNotFullAndRelevantStartedBetweenSep2014AndAug2019HeadingContent,
            staffChildsRatiosContent: level2QualificationNotFullAndRelevantStartedBetweenSeptember2014AndAugust2019RatioContent,
        }),
    }),
    createScenario({
        scenarioName: "Level 2 - Approved - started between September 2014 and August 2019 and awarded in June 2016 - Explanation of why the qualification is approved even though it's not full and relevant + Paediatric first aid certificate",
        scenarioId: 45,
        monthStarted: "01",
        yearStarted: "2015",
        monthAwarded: "06",
        yearAwarded: "2016",
        selectedLevel: 6,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-293",
        additionalRequirements: [noAtQuestionOne, noAtQuestionTwo, noAtQuestionThree],
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, level6QualificationApprovedLevel2ContentNFRAndPaediatricFirstAidCertificates, {
            fullAndRelevantHeading: level36QualificationNotFullAndRelevantStartedBetweenSep2014AndAug2019Heading,
            fullAndRelevantContent: level36QualificationNotFullAndRelevantStartedBetweenSep2014AndAug2019HeadingContent,
            staffChildsRatiosContent: level2QualificationNotFullAndRelevantStartedBetweenSeptember2014AndAugust2019RatioContent,
        }),
    }),
    createScenario({
        scenarioName: "Level 2 - Approved - started between September 2014 and August 2019 and awarded after June 2016 - Explanation of why the qualification is approved even though it's not full and relevant + Paediatric first aid certificate",
        scenarioId: 46,
        monthStarted: "01",
        yearStarted: "2015",
        monthAwarded: "07",
        yearAwarded: "2016",
        selectedLevel: 6,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-293",
        additionalRequirements: [noAtQuestionOne, noAtQuestionTwo, noAtQuestionThree],
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, level6QualificationApprovedLevel2ContentNFRAndPaediatricFirstAidCertificates, {
            fullAndRelevantHeading: level36QualificationNotFullAndRelevantStartedBetweenSep2014AndAug2019Heading,
            fullAndRelevantContent: level36QualificationNotFullAndRelevantStartedBetweenSep2014AndAug2019HeadingContent,
            staffChildsRatiosContent: level2QualificationNotFullAndRelevantStartedBetweenSeptember2014AndAugust2019RatioContent,
        }),
    }),

    createScenario({
        scenarioName: 'Level 2 - Not Approved - Null requirements',
        scenarioId: 47,
        monthStarted: "01",
        yearStarted: "2013",
        monthAwarded: "06",
        yearAwarded: "2018",
        selectedLevel: 6,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-179",
        additionalRequirements: [noAtQuestionOne, noAtQuestionTwo],
        expectedContent: createSingleRatioExpectedContent('Level 2', notApproved, '', {
            fullAndRelevantHeading: qualificationNotFullAndRelevantHeading,
            fullAndRelevantContent: qualificationNotFullAndRelevantHeadingContent,
            staffChildsRatiosContent: level2QualificationNotFullAndRelevantRatioContent,
        }),
    }),
    createScenario({
        scenarioName: 'Level 3 - Approved - Awarded before September 2014 - No other requirements',
        scenarioId: 48,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "04",
        yearAwarded: "2013",
        selectedLevel: 6,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-179",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 3', approved, noAdditionalRequirements),
    }),
    createScenario({
        scenarioName: "Level 3 - Approved - Awarded between September 2014 and May 2016 - Level 2 English qualification Exception: if the qualification is approved at level 6, there aren't any requirements",
        scenarioId: 49,
        monthStarted: "10",
        yearStarted: "2014",
        monthAwarded: "04",
        yearAwarded: "2015",
        selectedLevel: 6,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-292",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 3', approved, noAdditionalRequirements),
    }),
    createScenario({
        scenarioName: "Level 3 - Approved - Awarded between September 2014 and May 2016 - Level 2 English qualification Exception: if the qualification is approved at level 6, there aren't any requirements",
        scenarioId: 50,
        monthStarted: "10",
        yearStarted: "2014",
        monthAwarded: "04",
        yearAwarded: "2015",
        selectedLevel: 6,
        selectedAwardingOrganisation: "Nottingham Trent University",
        qualificationToSelect: "EYQ-283",
        additionalRequirements: [noAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 3', approved, approvedLevel3Level2English),
    }),
    createScenario({
        scenarioName: "Level 3 - Approved - Awarded in June 2016 - Level 2 English qualification + maybe Paediatric first aid certificate Exception: if the qualification is approved at level 6, there aren't any requirements",
        scenarioId: 51,
        monthStarted: "10",
        yearStarted: "2014",
        monthAwarded: "06",
        yearAwarded: "2016",
        selectedLevel: 6,
        selectedAwardingOrganisation: "Nottingham Trent University",
        qualificationToSelect: "EYQ-283",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 3', approved, noAdditionalRequirements),
    }),
    createScenario({
        scenarioName: "Level 3 - Approved - Awarded in June 2016 - Level 2 English qualification + maybe Paediatric first aid certificate Exception: if the qualification is approved at level 6, there aren't any requirements",
        scenarioId: 52,
        monthStarted: "10",
        yearStarted: "2014",
        monthAwarded: "06",
        yearAwarded: "2016",
        selectedLevel: 6,
        selectedAwardingOrganisation: "Nottingham Trent University",
        qualificationToSelect: "EYQ-283",
        additionalRequirements: [noAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 3', approved, approvedLevel3Level2EnglishMaybePaediatricFirstAidCertificate),
    }),
    createScenario({
        scenarioName: "Level 3 - Approved - Awarded after June 2016 - Level 2 English qualification + Paediatric first aid certificate Exception: if the qualification is approved at level 6, there aren't any requirements",
        scenarioId: 53,
        monthStarted: "10",
        yearStarted: "2014",
        monthAwarded: "07",
        yearAwarded: "2016",
        selectedLevel: 6,
        selectedAwardingOrganisation: "Nottingham Trent University",
        qualificationToSelect: "EYQ-283",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 3', approved, noAdditionalRequirements),
    }),
    createScenario({
        scenarioName: "Level 3 - Approved - Awarded after June 2016 - Level 2 English qualification + Paediatric first aid certificate Exception: if the qualification is approved at level 6, there aren't any requirements",
        scenarioId: 54,
        monthStarted: "10",
        yearStarted: "2014",
        monthAwarded: "07",
        yearAwarded: "2016",
        selectedLevel: 6,
        selectedAwardingOrganisation: "Nottingham Trent University",
        qualificationToSelect: "EYQ-283",
        additionalRequirements: [noAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 3', approved, approvedLevel3Level2EnglishPaediatricFirstAidCertificate),
    }),
    createScenario({
        scenarioName: 'Level 3 - Possible route available - Level 3 or above qualification that is NOT full and relevant - Experience-based route (EBR)',
        scenarioId: 55,
        monthStarted: "01",
        yearStarted: "2015",
        monthAwarded: "10",
        yearAwarded: "2015",
        selectedLevel: 6,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-292",
        additionalRequirements: [noAtQuestionOne, noAtQuestionTwo, noAtQuestionThree],
        expectedContent: createSingleRatioExpectedContent('Level 3', possibleRouteAvailable, ebrLevel3, {
            fullAndRelevantHeading: level36QualificationNotFullAndRelevantStartedBetweenSep2014AndAug2019Heading,
            fullAndRelevantContent: level36QualificationNotFullAndRelevantStartedBetweenSep2014AndAug2019HeadingContent,
            staffChildsRatiosContent: level2QualificationNotFullAndRelevantStartedBetweenSeptember2014AndAugust2019RatioContent,
        }),
    }),
    createScenario({
        scenarioName: 'Level 6 - Approved - No other requirements',
        scenarioId: 56,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "05",
        yearAwarded: "2016",
        selectedLevel: 6,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-192",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 6', approved, noAdditionalRequirements),
    }),
    createScenario({
        scenarioName: 'Level 6 - Not Approved - Level 6 qualification that is NOT a degree and it is NOT approved at level 6 - QTS, EYTS, EYPS',
        scenarioId: 57,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "05",
        yearAwarded: "2016",
        selectedLevel: 6,
        selectedAwardingOrganisation: "Open University OU",
        qualificationToSelect: "EYQ-179",
        additionalRequirements: [noAtQuestionOne, noAtQuestionTwo],
        expectedContent: createSingleRatioExpectedContent('Level 6', notApproved, level6NotApprovedContentQTSEYTSEYPS, {
            fullAndRelevantHeading: qualificationNotFullAndRelevantHeading,
            fullAndRelevantContent: qualificationNotFullAndRelevantHeadingContent,
            staffChildsRatiosContent: level2QualificationNotFullAndRelevantRatioContent,
        }),
    }),
    createScenario({
        scenarioName: 'Level 6 - Possible route available - Level 6 qualification that is a degree and it is NOT approved at level 6 - Early years initial teacher training (EYITT)',
        scenarioId: 58,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "05",
        yearAwarded: "2016",
        selectedLevel: 6,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-167",
        additionalRequirements: [noAtQuestionOne, noAtQuestionTwo, noAtQuestionThree],
        expectedContent: createSingleRatioExpectedContent('Level 6', possibleRouteAvailable, level6EBRContentEYITT, {
            fullAndRelevantHeading: qualificationNotFullAndRelevantHeading,
            fullAndRelevantContent: qualificationNotFullAndRelevantHeadingContent,
            staffChildsRatiosContent: level2QualificationNotFullAndRelevantRatioContent,
        }),
    }),
];

const level7Scenarios: Scenario[] = [
    createScenario({
        scenarioName: 'Level 2 - Approved - Awarded before June 2016 - No other requirements',
        scenarioId: 59,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "05",
        yearAwarded: "2016",
        selectedLevel: 7,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-206",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, noAdditionalRequirements),
    }),
    createScenario({
        scenarioName: "Level 2 - Approved - Awarded in June 2016 - Maybe Paediatric first aid certificate Exception: if the qualification is approved at level 6, there aren't any requirements",
        scenarioId: 60,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "06",
        yearAwarded: "2016",
        selectedLevel: 7,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-206",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, noAdditionalRequirements),
    }),
    createScenario({
        scenarioName: "Level 2 - Approved - Awarded after June 2016 - Maybe Paediatric first aid certificate Exception: if the qualification is approved at level 6, there aren't any requirements",
        scenarioId: 61,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "07",
        yearAwarded: "2016",
        selectedLevel: 7,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-206",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 2', approved, noAdditionalRequirements),
    }),
    createScenario({
        scenarioName: 'Level 2 - Not Approved - Null requirements',
        scenarioId: 62,
        monthStarted: "01",
        yearStarted: "2013",
        monthAwarded: "06",
        yearAwarded: "2018",
        selectedLevel: 7,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-206",
        additionalRequirements: [noAtQuestionOne, noAtQuestionTwo],
        expectedContent: createSingleRatioExpectedContent('Level 2', notApproved, '', {
            fullAndRelevantHeading: qualificationNotFullAndRelevantHeading,
            fullAndRelevantContent: qualificationNotFullAndRelevantHeadingContent,
            staffChildsRatiosContent: level2QualificationNotFullAndRelevantRatioContent,
        }),
    }),
    createScenario({
        scenarioName: 'Level 3 - Approved - Awarded before September 2014 - No other requirements',
        scenarioId: 63,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "04",
        yearAwarded: "2013",
        selectedLevel: 7,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-206",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 3', approved, noAdditionalRequirements),
    }),
    createScenario({
        scenarioName: 'Level 3 - Possible route available - Level 3 or above qualification that is NOT full and relevant - Experience-based route (EBR)',
        scenarioId: 64,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "10",
        yearAwarded: "2013",
        selectedLevel: 7,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-206",
        additionalRequirements: [noAtQuestionOne, noAtQuestionTwo],
        expectedContent: createSingleRatioExpectedContent('Level 3', possibleRouteAvailable, ebrLevel3, {
            fullAndRelevantHeading: qualificationNotFullAndRelevantHeading,
            fullAndRelevantContent: qualificationNotFullAndRelevantHeadingContent,
            staffChildsRatiosContent: level2QualificationNotFullAndRelevantRatioContent,
        }),
    }),
    createScenario({
        scenarioName: 'Level 6 - Approved - No other requirements',
        scenarioId: 65,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "05",
        yearAwarded: "2016",
        selectedLevel: 7,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-206",
        additionalRequirements: [yesAtQuestionOne],
        expectedContent: createSingleRatioExpectedContent('Level 6', approved, noAdditionalRequirements),
    }),
    createScenario({
        scenarioName: 'Level 6 - Not Approved - Level 6 qualification that is NOT a degree and it is NOT approved at level 6 - QTS, EYTS, EYPS',
        scenarioId: 66,
        monthStarted: "01",
        yearStarted: "2012",
        monthAwarded: "05",
        yearAwarded: "2016",
        selectedLevel: 7,
        selectedAwardingOrganisation: "Not on the list",
        qualificationToSelect: "EYQ-206",
        additionalRequirements: [noAtQuestionOne, noAtQuestionTwo],
        expectedContent: createSingleRatioExpectedContent('Level 6', notApproved, level6NotApprovedContentQTSEYTSEYPS, {
            fullAndRelevantHeading: qualificationNotFullAndRelevantHeading,
            fullAndRelevantContent: qualificationNotFullAndRelevantHeadingContent,
            staffChildsRatiosContent: level2QualificationNotFullAndRelevantRatioContent,
        }),
    }),
];

const regressionScenarios = [
    ...level2Scenarios,
    ...level3Scenarios,
    ...level4Scenarios,
    ...level5Scenarios,
    ...level6Scenarios,
    ...level7Scenarios,
];

regressionScenarios.forEach((scenario) => {
    test(`${scenario.scenarioId}. Qualification Level: ${scenario.selectedLevel} - Ratio ${scenario.scenarioName}`, async ({ context, page }) => {
        // Setup
        await startJourney(page, context);
        await checkingOwnQualificationOrSomeoneElsesPage(page, "#yes");
        await whereWasTheQualificationAwarded(page, "#england");
        await chooseStartDateOptionBasedOnDate(page, scenario.monthStarted, scenario.yearStarted);
        await whenWasQualificationAwarded(page, scenario.monthAwarded, scenario.yearAwarded);
        await whatLevelIsTheQualification(page, scenario.selectedLevel);
        if (scenario.selectedAwardingOrganisation === "Not on the list") {
            await selectNotOnTheListAsTheAwardingOrganisation(page);
        }
        else {
            await whatIsTheAwardingOrganisationValue(page, scenario.selectedAwardingOrganisation);
        }
        await checkYourAnswersPage(page);
        await selectQualification(page, scenario.qualificationToSelect);
        await confirmQualification(page, "#yes");

        if (scenario.additionalRequirements.length > 0) {
            for (const x of scenario.additionalRequirements) {
                await processAdditionalRequirement(page, scenario.qualificationToSelect, x.index, x.answer);
            }
            await confirmAdditonalRequirementsAnswers(page, scenario.qualificationToSelect);
        }

        // Assertions
        await checkDetailsPage(page, scenario.qualificationToSelect);

        for (const content of scenario.expectedContent) {

            await checkText(page, `#qualification-result-message-heading`, content.fullAndRelevantHeading, null, true);
            await checkText(page, `#qualification-result-message-body`, content.fullAndRelevantContent, null, true);

            for (const ratioRequirement of content.ratioRequirementContent) {
                await checkText(page, `#${ratioRequirement.headerId}`, ratioRequirement.level, null, true);

                await checkText(page, `#${ratioRequirement.approvalId}`, ratioRequirement.approvalStatus, null, true);

                if (ratioRequirement.expectedContent !== "") {
                    await checkText(page, `#${ratioRequirement.contentId}`, ratioRequirement.expectedContent, null, true);
                }
                else {
                    await doesNotExist(page, `#${ratioRequirement.contentId}`);
                }
            }

            if (content.staffChildsRatiosContent !== undefined) {
                await checkText(page, 'h2#ratio-heading + p', content.staffChildsRatiosContent);

                if (scenario.selectedLevel != 2) {
                    if (await page.locator('#ratio-additional-info').count() > 0) {
                        await checkText(page, '#ratio-additional-info', ratioRequirmentAlternativeRouteContent, null, true);
                    }
                    else {
                        await checkText(page, 'h2#ratio-heading + p + p', ratioRequirmentAlternativeRouteContent, null, true);
                    }
                }
            }
        }
    });
});
