name: Automated Storage Account Access Keys Rotation

on:
  schedule:
    # Runs at 2am, on the first of the month of feb, apr, jun, aug, oct, dec
    - cron: "0 2 1 2,4,6,8,10,12 *"

jobs:
  rotate-access-keys:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: ['development', 'staging', 'production']
    environment: ${{ matrix.target }}
    # Permissions for OIDC authentication
    permissions:
      id-token: write
      contents: write
      issues: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # Login to Azure using OIDC
      - name: Login to Azure CLI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Rotate keys for ${{ matrix.target }}
        uses: './.github/actions/storage-account-key-rotation'
        with:
          webapp_storage_account_name: ${{ vars.WEBAPP_STORAGE_ACCOUNT_NAME }}
          resource_name_prefix: ${{ vars.RESOURCE_NAME_PREFIX }}
          webapp_name: ${{ vars.WEBAPP_NAME }}