name: Automated Storage Account Access Keys Rotation

on:
  workflow_dispatch:
  schedule:
    # Runs at 2am, on the first of the month of feb, apr, jun, aug, oct, dec
    - cron: "0 2 1 2,4,6,8,10,12 *"

jobs:
  rotate-access-keys:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: ['development', 'staging', 'production']
    environment: ${{ matrix.target }}
    # Permissions for OIDC authentication
    permissions:
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # Login to Azure using OIDC
      - name: Login to Azure CLI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Rotate keys for ${{ matrix.target }}
        uses: './.github/actions/storage-account-key-rotation'
        with:
          webapp_storage_account_name: ${{ vars.WEBAPP_STORAGE_ACCOUNT_NAME }}
          resource_name_prefix: ${{ vars.RESOURCE_NAME_PREFIX }}
          webapp_name: ${{ vars.WEBAPP_NAME }}
          
  auto-approve:
    runs-on: ubuntu-22.04
    steps:
      
      # Allows the rotate-access-keys job to start and create the approval requests
      - name: Sleep for 30 seconds
        shell: bash
        run: sleep 30s
      - name: Auto-approve
        shell: bash
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/DFE-Digital/check-an-early-years-qualification/actions/runs/${{github.run_id}}/pending_deployments \
          -d '{"environment_ids":[2468357533,3407698866],"state":"approved","comment":"auto approved through workflow"}'