name: Build Image and Publish to GCR

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
      checked-out-sha:
        type: string
        required: true
    outputs:
        dockerImageTag: 
          description: "The image written to the GCR"
          value: ${{ jobs.build-image.outputs.dockerImageTag }}

concurrency:
     group: ${{ github.workflow }}-${{ github.event.inputs.environment }}
     cancel-in-progress: true

env:
    DOCKER_IMAGE: early-years-qualification
    GITHUB_CONTAINER_REGISTRY: ghcr.io
    ORG_NAME: dfe-digital

jobs:

    build-image:

        runs-on: ubuntu-22.04
        name: Build & Publish Image
        outputs:
          dockerImageTag: ${{ steps.image.outputs.dockerImageTag }}
        steps:

            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                ref: ${{ github.ref }}

            - name: GitHub Container Registry Login
              uses: docker/login-action@v3
              with:
                registry: ${{ env.GITHUB_CONTAINER_REGISTRY }}
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build Image & Publish To GCR
              uses: docker/build-push-action@v5
              with:
                context: ./
                file: ./src/Dfe.EarlyYearsQualification.Web/Dockerfile
                build-args: COMMIT_SHA=${{ inputs.checked-out-sha }}
                tags: |
                    ${{ env.GITHUB_CONTAINER_REGISTRY }}/${{ env.ORG_NAME }}/${{ env.DOCKER_IMAGE }}:main-${{ inputs.checked-out-sha }}
                push: true

            - name: Output Docker Image Tag
              id: image
              run: echo "dockerImageTag=${{ env.GITHUB_CONTAINER_REGISTRY }}/${{ env.ORG_NAME }}/${{ env.DOCKER_IMAGE }}:main-${{ inputs.checked-out-sha }}" >> $GITHUB_OUTPUT
