run-name: 'Cycle Storage Account Access Keys - ${{inputs.environment}}'
name: Cycle Storage Account Access Keys

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Azure environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production
jobs:
  cycle-access-keys:
    name: Update access keys for ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    # Permissions for OIDC authentication
    permissions:
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # Login to Azure using OIDC
      - name: Login to Azure CLI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Rotate keys for ${{ inputs.environment }}
        uses: './.github/actions/storage-account-key-rotation'
        with:
          webapp_storage_account_name: ${{ vars.WEBAPP_STORAGE_ACCOUNT_NAME }}
          resource_name_prefix: ${{ vars.RESOURCE_NAME_PREFIX }}
          webapp_name: ${{ vars.WEBAPP_NAME }}
          restart_slot: ${{ inputs.environment != 'development' }}
          slot_name: ${{ vars.WEBAPP_SLOT_NAME }}