run-name: 'Restart Service - ${{inputs.environment}}'
name: 'Restart Service'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Azure deployment environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production
            
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:

  restart-service:
    name: Restart
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    # Permissions for OIDC authentication
    permissions:
      id-token: write
      contents: write
      issues: write
    steps:
      # Login to Azure using OIDC
      - name: Login to Azure CLI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Restart Service
        uses: ./.github/actions/restart-app-service
        with:
          resource_name_prefix: ${{ vars.RESOURCE_NAME_PREFIX }}
          webapp_name: ${{ vars.WEBAPP_NAME }} 
