name: Run Load Tests
description: Runs k6 load tests against the staging (test) environment

on:
  workflow_dispatch:
  schedule: # only runs off main branch
    - cron: "40 3 * * TUE" # at 3.40 am, every Tuesday

jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment: staging # do not run against production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Set up k6"
        uses: grafana/setup-k6-action@v1
        with:
          k6-version: '1.0.0'

      - name: "Run local k6 load tests"
        uses: grafana/run-k6-action@v1
        id: run_tests
        env:
          CHALLENGE_PASSWORD: ${{ secrets.WEBAPP_E2E_ACCESS_KEY }}
          CUSTOM_DOMAIN: ${{ vars.SERVICE_GOV_UK_CUSTOM_DOMAIN_NAME }}/
          OPTIONS_SET: load
        with:
          path: |
            ./tests/Dfe.EarlyYearsQualification.LoadTests/run-tests.js
          cloud-run-locally: false

          
  auto-approve:
    runs-on: ubuntu-22.04
    steps:
      
      # Allows the run-tests job to start, and creates the approval requests
      - name: Sleep for 20 seconds
        shell: bash
        run: sleep 20s

      - name: Auto-approve
        shell: bash
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.STORAGE_ACCOUNT_KEY_ROTATION_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/DFE-Digital/check-an-early-years-qualification/actions/runs/${{github.run_id}}/pending_deployments \
          -d '{"environment_ids":[2468357533,3407698866],"state":"approved","comment":"auto approved through workflow"}'