name: Run Load Tests
description: Runs k6 load tests against the staging (test) environment

on:
  workflow_dispatch:
  schedule: # only runs off main branch
    - cron: "40 3 * * 0-4" # at 3.40 am, every Sunday through Thursday
  push: # remove this before completing the PR
    branches:
      - "feature/eyqb-1076-k6-in-pipeline"
  pull_request: # remove this before completing the PR
    branches:
      - "feature/eyqb-1076-k6-in-pipeline"
  issue_comment: # remove this before completing the PR

jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Set up k6"
        uses: grafana/setup-k6-action@v1
        with:
          k6-version: '1.0.0'

      - name: "Run local k6 load tests"
        uses: grafana/run-k6-action@v1
        id: run_tests
        env:
          CHALLENGE_PASSWORD: ${{ secrets.WEBAPP_E2E_ACCESS_KEY }}
          CUSTOM_DOMAIN: staging.check-an-early-years-qualification.service.gov.uk/
          OPTIONS_SET: load
        with:
          path: |
            ./tests/Dfe.EarlyYearsQualification.LoadTests/run-tests.js
          cloud-run-locally: false
