name: Validation Checks - Staging

on:
  workflow_dispatch:
  schedule:
    # Runs daily at 2am, Monday through Friday
    - cron: "0 2 * * 1-5"

jobs:

  validation-checks-staging:
    name: Run validation checks against staging
    runs-on: ubuntu-24.04
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Playwright
        uses: ./.github/actions/install-playwright
      - name: Run Playwright validation tests
        uses: ./.github/actions/run-playwright-tests
        with:
          webapp_url: "${{ vars.SERVICE_GOV_UK_CUSTOM_DOMAIN_NAME }}"
          auth_secret: ${{ secrets.WEBAPP_E2E_ACCESS_KEY }}
          test_type: "validation"
  
  auto-approve:
    runs-on: ubuntu-24.04
    steps:

      # Allows the run-tests job to start, and creates the approval requests
      - name: Sleep for 20 seconds
        shell: bash
        run: sleep 20s

      - name: Auto-approve
        shell: bash
        env:
          STORAGE_TOKEN: ${{ secrets.STORAGE_ACCOUNT_KEY_ROTATION_TOKEN }}
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $STORAGE_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/DFE-Digital/check-an-early-years-qualification/actions/runs/${{github.run_id}}/pending_deployments \
          -d '{"environment_ids":[2468357533,3407698866],"state":"approved","comment":"auto approved through workflow"}'