name: Storage account key rotation
description: Used to rotate the keys of the storage account

inputs:
  webapp_storage_account_name:
    required: true
    description: The storage account name for the webapp
  resource_name_prefix:
    required: true
    description: The resource name prefix
  webapp_name:
    required: true
    description: The name of the webapp
  restart_slot:
    required: false
    description: A flag indicating whether to restart the slot or not
    default: 'false'
  slot_name:
    required: true
    description: The name of the slot
    default: 'production'
  secret_name:
    required: false
    description: The name of the KeyVault secret
    default: 'Storage--ConnectionString'

runs:
  using: composite
  steps:
    # Get the key2 connection, update KV and restart web app
    - name: Get the key2 connection string and update KeyVault secret
      shell: bash
      env:
        WEBAPP_STORAGE_ACCOUNT_NAME: ${{ inputs.webapp_storage_account_name }}
        RESOURCE_NAME_PREFIX: ${{ inputs.resource_name_prefix }}
        WEBAPP_NAME: ${{ inputs.webapp_name }}
      run: |
        connectionString=$(az storage account show-connection-string --name "${WEBAPP_STORAGE_ACCOUNT_NAME}" --resource-group "${RESOURCE_NAME_PREFIX}-rg" --key key2 --output tsv)
        az keyvault secret set --name ${{ inputs.secret_name }} --vault-name "${RESOURCE_NAME_PREFIX}-kv" --value "$connectionString"
        az webapp restart --resource-group "${RESOURCE_NAME_PREFIX}-rg" --name "${WEBAPP_NAME}"

    # Update the key1 access key, update KV and restart
    - name: Update the key1 access key and update KeyVault secret
      shell: bash
      env:
        WEBAPP_STORAGE_ACCOUNT_NAME: ${{ inputs.webapp_storage_account_name }}
        RESOURCE_NAME_PREFIX: ${{ inputs.resource_name_prefix }}
        WEBAPP_NAME: ${{ inputs.webapp_name }}
      run: |
        az storage account keys renew --account-name "${WEBAPP_STORAGE_ACCOUNT_NAME}" --resource-group "${RESOURCE_NAME_PREFIX}-rg" --key key1
        connectionString=$(az storage account show-connection-string --name "${WEBAPP_STORAGE_ACCOUNT_NAME}" --resource-group "${RESOURCE_NAME_PREFIX}-rg" --key key1 --output tsv)
        az keyvault secret set --name ${{ inputs.secret_name }} --vault-name "${RESOURCE_NAME_PREFIX}-kv" --value "$connectionString"
        az webapp restart --resource-group "${RESOURCE_NAME_PREFIX}-rg" --name "${WEBAPP_NAME}"

    # Update the key2 access key
    - name: Update the key2 access key
      shell: bash
      env:
        WEBAPP_STORAGE_ACCOUNT_NAME: ${{ inputs.webapp_storage_account_name }}
        RESOURCE_NAME_PREFIX: ${{ inputs.resource_name_prefix }}
      run: |
        az storage account keys renew --account-name "${WEBAPP_STORAGE_ACCOUNT_NAME}" --resource-group "${RESOURCE_NAME_PREFIX}-rg" --key key2

    # Restart the slot
    - name: Restart the slot
      if: ${{ inputs.restart_slot == 'true' }}
      shell: bash
      env:
        RESOURCE_NAME_PREFIX: ${{ inputs.resource_name_prefix }}
        WEBAPP_NAME: ${{ inputs.webapp_name }}
        SLOT_NAME: ${{ inputs.slot_name }}
      run: |
        az webapp restart --resource-group "${RESOURCE_NAME_PREFIX}-rg" --name "${WEBAPP_NAME}" --slot "${SLOT_NAME}"
